[hotreload]
  suffixes = [".go"]
  ignore = []

[app]
  #app 名称
  name = "you_project_name"
  #app url
  url  = "http://localhost"
  #app 文档地址
  doc = "./apidoc"
  addr = ":80"
  #单元测试调试信息
  debug = false

  [app.logger]
    level = "INFO"
    name = "application"

#数据库驱动
[database]
    dirver = "mysql"

[mysql]
   databaseHost = "192.168.99.100"
   databasePort = "33061"
   databaseName = "bi_functions"
   databaseUserName ="root"
   databasePassword ="mysql"

[mongodb]
  connect = "mongodb://root:root@192.168.99.100:27017/admin"

[sqlite]
  connect = "/tmp/gorm.db"

#reids
[redis]
  Addr = "127.0.0.1:6379"
  Password = ""
  DB = 0

[neo4j]
    connect = "http://10.10.43.111:7474/db/data"

[test]
    #测试登陆用户名
    LoginUserName = "leroy"
    #测试用户名
    LoginName = "leroylee"
    #测试用户密码
    LoginPwd = "leroy"
    #测试数据库驱动
    DataBaseDriver = "sqlite3"
    #测试数据库
    DataBaseConnect = "tmp/gorm.db"
